[project]
authors = ["@jasmcaus", "@xburralabs"]
entry = "main.sw"
license = "Apache-2.0"
name = "vault-pricefeed"

[dependencies]
core_interfaces = { path = "../interfaces" }
helpers = { path = "../../helpers" }
interfaces = { path = "../../interfaces" }
